minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@types/node@26.5.1'

trustPolicy: no-downgrade

update:
  ignoreDeps:
    - typescript@7

shellEmulator: true

allowBuilds:
  esbuild: true

onlyBuiltDependencies:
  - esbuild
